import { Logger, ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import * as express from 'express';
import { existsSync, mkdirSync } from 'fs';
import { join, resolve } from 'path';
import { AppModule } from './app.module';
import { HttpExceptionFilter } from './common/filters/http-exception.filter';
import { TransformInterceptor } from './common/interceptors/transform.interceptor';

async function bootstrap() {
  const logger = new Logger('Bootstrap');
  const app = await NestFactory.create(AppModule, { rawBody: false });

  // Ensure JSON body parser handles UTF-8 correctly
  app.use(express.json({ limit: '50mb' }));
  app.use(express.urlencoded({ extended: true, limit: '50mb' }));

  // Serve cover images statically (before global prefix, before ServeStaticModule)
  // 优先使用 CACHE_PATH，未设置时回退到 NAS_EBOOK_PATH/covers
  const cachePath = process.env.CACHE_PATH;
  const nasEbookPath = resolve(process.env.NAS_EBOOK_PATH || '/data/ebooks');
  const coversPath = cachePath
    ? join(resolve(cachePath), 'covers')
    : join(nasEbookPath, 'covers');
  logger.log(`Serving covers from: ${coversPath}`);
  app.use('/covers', express.static(coversPath));

  // Serve TTS audio cache (mp3 files generated by tts-service).
  // Falls back to <cwd>/.tts-cache when /data/audio doesn't exist (local dev).
  const ttsAudioEnv = process.env.TTS_AUDIO_CACHE_DIR || '/data/audio';
  let ttsAudioPath = resolve(ttsAudioEnv);
  if (!existsSync(ttsAudioPath)) {
    ttsAudioPath = resolve(process.cwd(), '.tts-cache');
    if (!existsSync(ttsAudioPath)) {
      mkdirSync(ttsAudioPath, { recursive: true });
    }
    logger.warn(`TTS audio static dir fallback: ${ttsAudioPath} (env ${ttsAudioEnv} not found)`);
  }
  logger.log(`Serving TTS audio from: ${ttsAudioPath}`);
  app.use('/audio', express.static(ttsAudioPath));

  // Global prefix
  app.setGlobalPrefix('api');

  // CORS
  const corsOrigins = process.env.CORS_ORIGINS || '*';
  app.enableCors({
    origin: corsOrigins === '*' ? true : corsOrigins.split(','),
    credentials: true,
  });

  // Global pipes
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
      transformOptions: { enableImplicitConversion: true },
    }),
  );

  // Global filters & interceptors
  app.useGlobalFilters(new HttpExceptionFilter());
  app.useGlobalInterceptors(new TransformInterceptor());

  // Swagger
  const config = new DocumentBuilder()
    .setTitle('BookDock API')
    .setDescription('BookDock E-Book Reader API Documentation')
    .setVersion('1.0')
    .addBearerAuth()
    .build();
  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api/docs', app, document);

  const port = process.env.PORT || 3000;
  await app.listen(port);
  logger.log(`BookDock API running on http://0.0.0.0:${port}/api`);
  logger.log(`Swagger docs: http://0.0.0.0:${port}/api/docs`);
}

bootstrap();
